using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Report
{
    public class StructPassRange
    {
        public string Color { get; set; }
        public double Front_dE_Minus15_PassRangeValue { get; set; }
        public double Front_dE_Minus15_PassRangeMinusValue { get; set; }
        public double Front_dE_Minus15_PassRangePlusValue { get; set; }
        public double Front_dL_Minus15_PassRangeValue { get; set; }
        public double Front_dL_Minus15_PassRangeMinusValue { get; set; }
        public double Front_dL_Minus15_PassRangePlusValue { get; set; }
        public double Front_da_Minus15_PassRangeValue { get; set; }
        public double Front_da_Minus15_PassRangeMinusValue { get; set; }
        public double Front_da_Minus15_PassRangePlusValue { get; set; }
        public double Front_db_Minus15_PassRangeValue { get; set; }
        public double Front_db_Minus15_PassRangeMinusValue { get; set; }
        public double Front_db_Minus15_PassRangePlusValue { get; set; }
        public double Front_dE_15_PassRangeValue { get; set; }
        public double Front_dE_15_PassRangeMinusValue { get; set; }
        public double Front_dE_15_PassRangePlusValue { get; set; }
        public double Front_dL_15_PassRangeValue { get; set; }
        public double Front_dL_15_PassRangeMinusValue { get; set; }
        public double Front_dL_15_PassRangePlusValue { get; set; }
        public double Front_da_15_PassRangeValue { get; set; }
        public double Front_da_15_PassRangeMinusValue { get; set; }
        public double Front_da_15_PassRangePlusValue { get; set; }
        public double Front_db_15_PassRangeValue { get; set; }
        public double Front_db_15_PassRangeMinusValue { get; set; }
        public double Front_db_15_PassRangePlusValue { get; set; }
        public double Front_dE_25_PassRangeValue { get; set; }
        public double Front_dE_25_PassRangeMinusValue { get; set; }
        public double Front_dE_25_PassRangePlusValue { get; set; }
        public double Front_dL_25_PassRangeValue { get; set; }
        public double Front_dL_25_PassRangeMinusValue { get; set; }
        public double Front_dL_25_PassRangePlusValue { get; set; }
        public double Front_da_25_PassRangeValue { get; set; }
        public double Front_da_25_PassRangeMinusValue { get; set; }
        public double Front_da_25_PassRangePlusValue { get; set; }
        public double Front_db_25_PassRangeValue { get; set; }
        public double Front_db_25_PassRangeMinusValue { get; set; }
        public double Front_db_25_PassRangePlusValue { get; set; }
        public double Front_dE_45_PassRangeValue { get; set; }
        public double Front_dE_45_PassRangeMinusValue { get; set; }
        public double Front_dE_45_PassRangePlusValue { get; set; }
        public double Front_dL_45_PassRangeValue { get; set; }
        public double Front_dL_45_PassRangeMinusValue { get; set; }
        public double Front_dL_45_PassRangePlusValue { get; set; }
        public double Front_da_45_PassRangeValue { get; set; }
        public double Front_da_45_PassRangeMinusValue { get; set; }
        public double Front_da_45_PassRangePlusValue { get; set; }
        public double Front_db_45_PassRangeValue { get; set; }
        public double Front_db_45_PassRangeMinusValue { get; set; }
        public double Front_db_45_PassRangePlusValue { get; set; }
        public double Front_dE_75_PassRangeValue { get; set; }
        public double Front_dE_75_PassRangeMinusValue { get; set; }
        public double Front_dE_75_PassRangePlusValue { get; set; }
        public double Front_dL_75_PassRangeValue { get; set; }
        public double Front_dL_75_PassRangeMinusValue { get; set; }
        public double Front_dL_75_PassRangePlusValue { get; set; }
        public double Front_da_75_PassRangeValue { get; set; }
        public double Front_da_75_PassRangeMinusValue { get; set; }
        public double Front_da_75_PassRangePlusValue { get; set; }
        public double Front_db_75_PassRangeValue { get; set; }
        public double Front_db_75_PassRangeMinusValue { get; set; }
        public double Front_db_75_PassRangePlusValue { get; set; }
        public double Front_dE_110_PassRangeValue { get; set; }
        public double Front_dE_110_PassRangeMinusValue { get; set; }
        public double Front_dE_110_PassRangePlusValue { get; set; }
        public double Front_dL_110_PassRangeValue { get; set; }
        public double Front_dL_110_PassRangeMinusValue { get; set; }
        public double Front_dL_110_PassRangePlusValue { get; set; }
        public double Front_da_110_PassRangeValue { get; set; }
        public double Front_da_110_PassRangeMinusValue { get; set; }
        public double Front_da_110_PassRangePlusValue { get; set; }
        public double Front_db_110_PassRangeValue { get; set; }
        public double Front_db_110_PassRangeMinusValue { get; set; }
        public double Front_db_110_PassRangePlusValue { get; set; }
        public double Rear_dE_Minus15_PassRangeValue { get; set; }
        public double Rear_dE_Minus15_PassRangeMinusValue { get; set; }
        public double Rear_dE_Minus15_PassRangePlusValue { get; set; }
        public double Rear_dL_Minus15_PassRangeValue { get; set; }
        public double Rear_dL_Minus15_PassRangeMinusValue { get; set; }
        public double Rear_dL_Minus15_PassRangePlusValue { get; set; }
        public double Rear_da_Minus15_PassRangeValue { get; set; }
        public double Rear_da_Minus15_PassRangeMinusValue { get; set; }
        public double Rear_da_Minus15_PassRangePlusValue { get; set; }
        public double Rear_db_Minus15_PassRangeValue { get; set; }
        public double Rear_db_Minus15_PassRangeMinusValue { get; set; }
        public double Rear_db_Minus15_PassRangePlusValue { get; set; }
        public double Rear_dE_15_PassRangeValue { get; set; }
        public double Rear_dE_15_PassRangeMinusValue { get; set; }
        public double Rear_dE_15_PassRangePlusValue { get; set; }
        public double Rear_dL_15_PassRangeValue { get; set; }
        public double Rear_dL_15_PassRangeMinusValue { get; set; }
        public double Rear_dL_15_PassRangePlusValue { get; set; }
        public double Rear_da_15_PassRangeValue { get; set; }
        public double Rear_da_15_PassRangeMinusValue { get; set; }
        public double Rear_da_15_PassRangePlusValue { get; set; }
        public double Rear_db_15_PassRangeValue { get; set; }
        public double Rear_db_15_PassRangeMinusValue { get; set; }
        public double Rear_db_15_PassRangePlusValue { get; set; }
        public double Rear_dE_25_PassRangeValue { get; set; }
        public double Rear_dE_25_PassRangeMinusValue { get; set; }
        public double Rear_dE_25_PassRangePlusValue { get; set; }
        public double Rear_dL_25_PassRangeValue { get; set; }
        public double Rear_dL_25_PassRangeMinusValue { get; set; }
        public double Rear_dL_25_PassRangePlusValue { get; set; }
        public double Rear_da_25_PassRangeValue { get; set; }
        public double Rear_da_25_PassRangeMinusValue { get; set; }
        public double Rear_da_25_PassRangePlusValue { get; set; }
        public double Rear_db_25_PassRangeValue { get; set; }
        public double Rear_db_25_PassRangeMinusValue { get; set; }
        public double Rear_db_25_PassRangePlusValue { get; set; }
        public double Rear_dE_45_PassRangeValue { get; set; }
        public double Rear_dE_45_PassRangeMinusValue { get; set; }
        public double Rear_dE_45_PassRangePlusValue { get; set; }
        public double Rear_dL_45_PassRangeValue { get; set; }
        public double Rear_dL_45_PassRangeMinusValue { get; set; }
        public double Rear_dL_45_PassRangePlusValue { get; set; }
        public double Rear_da_45_PassRangeValue { get; set; }
        public double Rear_da_45_PassRangeMinusValue { get; set; }
        public double Rear_da_45_PassRangePlusValue { get; set; }
        public double Rear_db_45_PassRangeValue { get; set; }
        public double Rear_db_45_PassRangeMinusValue { get; set; }
        public double Rear_db_45_PassRangePlusValue { get; set; }
        public double Rear_dE_75_PassRangeValue { get; set; }
        public double Rear_dE_75_PassRangeMinusValue { get; set; }
        public double Rear_dE_75_PassRangePlusValue { get; set; }
        public double Rear_dL_75_PassRangeValue { get; set; }
        public double Rear_dL_75_PassRangeMinusValue { get; set; }
        public double Rear_dL_75_PassRangePlusValue { get; set; }
        public double Rear_da_75_PassRangeValue { get; set; }
        public double Rear_da_75_PassRangeMinusValue { get; set; }
        public double Rear_da_75_PassRangePlusValue { get; set; }
        public double Rear_db_75_PassRangeValue { get; set; }
        public double Rear_db_75_PassRangeMinusValue { get; set; }
        public double Rear_db_75_PassRangePlusValue { get; set; }
        public double Rear_dE_110_PassRangeValue { get; set; }
        public double Rear_dE_110_PassRangeMinusValue { get; set; }
        public double Rear_dE_110_PassRangePlusValue { get; set; }
        public double Rear_dL_110_PassRangeValue { get; set; }
        public double Rear_dL_110_PassRangeMinusValue { get; set; }
        public double Rear_dL_110_PassRangePlusValue { get; set; }
        public double Rear_da_110_PassRangeValue { get; set; }
        public double Rear_da_110_PassRangeMinusValue { get; set; }
        public double Rear_da_110_PassRangePlusValue { get; set; }
        public double Rear_db_110_PassRangeValue { get; set; }
        public double Rear_db_110_PassRangeMinusValue { get; set; }
        public double Rear_db_110_PassRangePlusValue { get; set; }
    }
}
